stages:
  - test

test_async:
  stage: test
  script:
   - tar -xf /home/gitlab-runner/nodeModules.tar
   - tar -xf /home/gitlab-runner/nodeModulesPublic.tar
   - cd public
   - ./node_modules/.bin/grunt dev
   - cd ..
   - pm2 start app.js
   - ./node_modules/.bin/chimp
