stages:
  - test

test_async:
  stage: test
  script:
   - pm2 delete all
   - tar -xf /home/ukwDisplayAdministration/nodeModulesArchiv/nodeModules.tar
   - tar -xf /home/ukwDisplayAdministration/nodeModulesArchiv/nodeModulesPublic.tar
   - tar -xf /home/ukwDisplayAdministration/nodeModulesArchiv/nodeModulesChimp.tar
   - cd public
   - ./node_modules/.bin/grunt dev
   - cd ..
   - pm2 start app.js
   - ./node_modules/.bin/chimp
